import {test} from 'node:test';
import assert from 'node:assert/strict';
import {pavilion,Building} from './building';
function seeded(){const b=pavilion();for(const h of b.habitats.filter(h=>h.kind==='column'))b.inoculate([h.p[0],.4,h.p[2]]);return b;}
test('building grows columns, walls and shelter while preserving openings',()=>{const b=seeded();for(let i=0;i<280;i++)b.step();assert.ok(b.cells.some(c=>c.kind==='roof'));assert.ok(b.cells.filter(c=>c.kind==='wall').length>100);assert.ok(b.coverage('roof')>65,`roof coverage ${b.coverage('roof')}`);assert.ok(b.cells.every(c=>!b.habitats.some(h=>h.kind==='void'&&b.contains(h,c.p))));});
test('growth needs inoculation and connected habitats',()=>{const b=pavilion();for(let i=0;i<20;i++)b.step();assert.equal(b.cells.length,0);b.add('roof',[10,8,10],[2,.6,2]);b.inoculate([-5.6,.4,-4]);for(let i=0;i<100;i++)b.step();assert.ok(!b.cells.some(c=>c.p[0]>9));});
test('seeds reproduce growth and climate changes its pace',()=>{const a=seeded(),b=seeded(),c=seeded();c.moisture=0;c.vitality=0;for(let i=0;i<40;i++){a.step();b.step();c.step();}assert.deepEqual(a.cells,b.cells);assert.ok(c.cells.length<a.cells.length);});
test('building save resumes exact random state and reset preserves habitats',()=>{const a=seeded();for(let i=0;i<30;i++)a.step();const b=Building.load(a.save());for(let i=0;i<20;i++){a.step();b.step();}assert.equal(a.save(),b.save());a.reset();assert.equal(a.cells.length,0);assert.ok(a.habitats.length>0);});
test('fiber parents come from existing neighboring tissue and survive save',()=>{const b=seeded();for(let i=0;i<50;i++)b.step();const seen=new Set<string>();const key=(p:number[])=>p.map(x=>Math.round(x/.4)).join(',');for(const c of b.cells){if(c.parent){assert.ok(seen.has(key(c.parent)));assert.ok(Math.hypot(...c.p.map((v,i)=>v-c.parent![i]))<.58);}seen.add(key(c.p));}assert.ok(b.cells.filter(c=>c.parent).length>b.cells.length*.9);assert.deepEqual(Building.load(b.save()).cells,b.cells);});
test('an existing building can extend upward, resume, and replenish without reset',()=>{const b=seeded();for(let i=0;i<160;i++)b.step();const old=b.cells.length;b.add('column',[-5.6,7.2,-4],[1.2,4.8,1.2]);b.rebuildFrontier();for(let i=0;i<100;i++)b.step();assert.ok(b.cells.length>old);assert.ok(b.cells.some(c=>c.p[1]>8));b.budget=b.spent;b.step();const stopped=b.cells.length;b.replenish();b.add('column',[12,9.6,0],[1.2,3.2,1.2]);assert.ok(b.inoculate([12,8,0]));for(let i=0;i<20;i++)b.step();assert.ok(b.cells.length>stopped);assert.ok(b.cells.some(c=>c.p[0]>11&&c.p[1]>8));});
