import {useEffect,useMemo,useRef} from 'react';
import {Canvas,useFrame,useThree} from '@react-three/fiber';
import {OrbitControls,Grid,Text} from '@react-three/drei';
import {RoundedBoxGeometry} from 'three/examples/jsm/geometries/RoundedBoxGeometry.js';
import * as THREE from 'three';
import Fibers from './Fibers';
import {Building,Point,maxCells} from '../simulation/building';
const camera={position:[18,13,20] as Point,fov:43};
function View({view}:{view:string}){const {camera,controls}=useThree();useEffect(()=>{camera.position.set(...(view==='plan'?[0,26,.01]:view==='inside'?[0,2.2,10]:[18,13,20]) as Point);if(controls){const c=controls as unknown as {target:THREE.Vector3;update:()=>void};c.target.set(0,view==='inside'?2.2:2,0);c.update();}camera.lookAt(0,2,0)},[view,camera,controls]);return null;}
function Tissue({b,roof,cut,mode}:{b:Building;roof:boolean;cut:boolean;mode:string}){const ref=useRef<THREE.InstancedMesh>(null);const geo=useMemo(()=>new RoundedBoxGeometry(1,1,1,2,.18),[]);const dummy=useMemo(()=>new THREE.Object3D(),[]);const color=useMemo(()=>new THREE.Color(),[]);useFrame(()=>{if(!ref.current)return;let i=0;for(const c of b.cells){if(!roof&&c.kind==='roof'||cut&&c.p[2]>1||mode==='woven'&&b.time-c.born<5)continue;dummy.position.set(...c.p);const maturity=Math.min(1,(b.time-c.born+.25)/4);const s=mode==='cells'?.13:.27+maturity*.15;dummy.scale.set(s,s,s);dummy.rotation.set(0,(c.vigor-.85)*.25,0);dummy.updateMatrix();ref.current.setMatrixAt(i,dummy.matrix);color.set(mode==='growth'?(maturity<.65?'#bada8b':'#71876b'):c.kind==='roof'?'#c8c8a9':'#ddd8bb');color.multiplyScalar(.86+c.vigor*.15);ref.current.setColorAt(i++,color);}ref.current.count=i;ref.current.instanceMatrix.needsUpdate=true;if(ref.current.instanceColor)ref.current.instanceColor.needsUpdate=true;});return <instancedMesh ref={ref} args={[geo,undefined,maxCells]} castShadow receiveShadow frustumCulled={false}><meshStandardMaterial roughness={.94}/></instancedMesh>}
function Human({p}:{p:Point}){return <group position={p}><mesh position={[0,1.54,0]}><sphereGeometry args={[.12,12,12]}/><meshStandardMaterial color="#849385"/></mesh><mesh position={[0,1.12,0]}><capsuleGeometry args={[.13,.52,4,8]}/><meshStandardMaterial color="#849385"/></mesh>{[-.085,.085].map(x=><mesh key={x} position={[x,.43,0]}><capsuleGeometry args={[.05,.69,4,6]}/><meshStandardMaterial color="#849385"/></mesh>)}</group>}
export default function BuildingWorld({b,tool,place,view,guides,roof,cut,mode,elevation}:{b:Building;tool:string;place:(p:Point)=>void;view:string;guides:boolean;roof:boolean;cut:boolean;mode:string;elevation:number}){return <Canvas shadows camera={camera} dpr={[1,1.5]}><color attach="background" args={['#141c1b']}/><ambientLight intensity={1.25}/><directionalLight position={[8,18,10]} intensity={2.6} castShadow shadow-mapSize={[2048,2048]} shadow-camera-left={-15} shadow-camera-right={15} shadow-camera-top={15} shadow-camera-bottom={-15}/><Grid args={[60,60]} position={[0,-.22,0]} cellSize={1} sectionSize={5} cellColor="#303d33" sectionColor="#465446" fadeDistance={45}/><mesh position={[0,-.13,0]} receiveShadow><boxGeometry args={[15.2,.24,12]}/><meshStandardMaterial color="#596254" roughness={1}/></mesh><mesh rotation={[-Math.PI/2,0,0]} position={[0,-.26,0]} receiveShadow><planeGeometry args={[150,150]}/><meshStandardMaterial color="#19221c"/></mesh>{mode!=='fibers'&&<Tissue b={b} roof={roof} cut={cut} mode={mode}/>}{['fibers','woven'].includes(mode)&&<Fibers b={b} roof={roof} cut={cut}/>} {guides&&b.habitats.filter(h=>h.kind!=='roof'||roof).map(h=><mesh key={h.id} position={h.p}><boxGeometry args={h.size}/><meshBasicMaterial color={h.kind==='void'?'#d7af80':h.kind==='nutrient'?'#99c879':'#b4caa1'} wireframe transparent opacity={h.kind==='void'?.27:.12}/></mesh>)}<Text position={[0,-.005,6.6]} rotation={[-Math.PI/2,0,0]} fontSize={.19} color="#a9baa0">12.8 M / LIVING ENVELOPE</Text><Human p={[2,.02,1]}/><Human p={[-1,.02,6]}/><mesh position={[3,.22,-1.4]}><boxGeometry args={[2.2,.38,.65]}/><meshStandardMaterial color="#697261"/></mesh><mesh rotation={[-Math.PI/2,0,0]} position={[0,elevation,0]} onClick={e=>{if(tool!=='navigate'){e.stopPropagation();place([e.point.x,elevation,e.point.z]);}}}><planeGeometry args={[80,80]}/><meshBasicMaterial transparent opacity={0} depthWrite={false}/></mesh><OrbitControls makeDefault enableRotate={tool==='navigate'} enablePan={tool==='navigate'} minDistance={4} maxDistance={100} maxPolarAngle={Math.PI/2-.03}/><View view={view}/></Canvas>}



