import {useState} from 'react';
import {Organism} from './simulation/organism';
import {exportOrganism,type ExportFormat,type ExportOptions} from './exporting/organismExport';
const formats:[ExportFormat,string,string][]=[['experiment','Experiment JSON','Complete organism, food, protected spaces, and growth state. Import to continue later.'],['obj-lines','OBJ centerlines','Lightweight 3D polylines for CAD and curve editing. No strand thickness.'],['obj-mesh','OBJ strand mesh','Mature strand geometry for 3D modeling and rendering.'],['stl','STL strand mesh','Binary triangle mesh. Capped strands; intersections may need cleanup.']];
export default function ExportDialog({o,close,notify}:{o:Organism;close:()=>void;notify:(message:string)=>void}){
 const [format,setFormat]=useState<ExportFormat>('experiment'),[units,setUnits]=useState<ExportOptions['units']>('m'),[detail,setDetail]=useState<ExportOptions['detail']>('low'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const download=async()=>{setBusy(true);setError('');try{const result=exportOrganism(o,{format,units,detail});const url=URL.createObjectURL(new Blob([result.data],{type:result.mime}));const a=document.createElement('a');a.href=url;a.download=result.name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);notify(`Exported ${result.name}`);close();}catch(e){setError(e instanceof Error?e.message:'Could not export this organism.');}finally{setBusy(false)}};
 return <div className="export-backdrop" onKeyDown={e=>{if(e.key==='Escape'&&!busy)close()}}><section className="export-dialog" role="dialog" aria-modal="true" aria-labelledby="export-title"><div className="section-title">TAKE YOUR CULTIVATION WITH YOU<button aria-label="Close export" onClick={close} disabled={busy}>×</button></div><h2 id="export-title">Export organism</h2><p>{o.edges.filter(e=>e.alive).length.toLocaleString()} living strands · seed {o.seed} · {Math.floor(o.time)} cycles</p><div className="export-formats">{formats.map(([id,name,description])=><label key={id} className={format===id?'chosen':''}><input autoFocus={id==='experiment'} type="radio" name="export-format" value={id} checked={format===id} onChange={()=>setFormat(id)}/><span><strong>{name}</strong><small>{description}</small></span></label>)}</div>{format!=='experiment'&&<div className="export-settings"><label>Geometry units<select aria-label="Export units" value={units} onChange={e=>setUnits(e.target.value as 'm'|'mm')}><option value="m">Meters</option><option value="mm">Millimeters</option></select></label>{format!=='obj-lines'&&<label>Mesh detail<select aria-label="Mesh detail" value={detail} onChange={e=>setDetail(e.target.value as 'low'|'high')}><option value="low">Lightweight · 6 sides</option><option value="high">Smooth · 10 sides</option></select></label>}</div>}<p className="export-note">{format==='experiment'?'Experiment files preserve all simulation data. Geometry unit settings do not change saved experiments.':'Exports include living strands only, fully extended, with Y up. Ground, food, protected spaces, and gumballs are excluded. OBJ/STL files do not reliably encode units; match the selected units when importing.'}</p>{error&&<p role="alert" className="export-error">{error}</p>}<button className="export-download" disabled={busy} onClick={download}>{busy?'Preparing export…':'Download export'}</button></section></div>;
}

